Updated file `catch.hpp` so that `make` runs with GCC 11.
New `catch.hpp` (2021) is from:
https://github.com/catchorg/Catch2/releases/tag/v2.13.7

Old `catch.hpp` (2020) fails to compile with GCC 11 on Ubuntu 21.10:
```
$ g++ --version
g++ (Ubuntu 11.2.0-7ubuntu2) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ make
Using CC=gcc
Using CXX=g++
Using LD=g++
Compiling with CUDD
Using libreadline
Using pthreads
Found GCC_VERSION 11
Found GCC_MAJOR>=4
Found GCC_MINOR>=6
Using CFLAGS=-Wall -Wno-parentheses -Wno-unused-function -Wno-write-strings -Wno-sign-compare -DLIN64 -DSIZEOF_VOID_P=8 -DSIZEOF_LONG=8 -DSIZEOF_INT=4 -DABC_USE_CUDD=1 -DABC_USE_READLINE  -DABC_USE_PTHREADS -Wno-unused-but-set-variable -D __STDC_LIMIT_MACROS -D __STDC_FORMAT_MACROS
`` Compiling: /src/extRegression/regression.cc
In file included from /usr/include/signal.h:328,
                 from src/extRegression/catch.hpp:8034,
                 from src/extRegression/regression.cc:19:
src/extRegression/catch.hpp:10822:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10822 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from src/extRegression/catch.hpp:8034,
                 from src/extRegression/regression.cc:19:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from src/extRegression/regression.cc:19:
src/extRegression/catch.hpp:10881:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10881 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
make: *** [Makefile:158: src/extRegression/regression.o] Error 1
```